### ISSUE TITLE
Can't search current tabs on Mojawe macOS

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#15]
Get this:

![2018-09-25 at 01 04](https://user-images.githubusercontent.com/6391776/45983921-069a4600-c05f-11e8-8e26-2aea6eb028db.png)

Here is log from the workflow:

```
Starting debug for 'Safari Assistant'

[2018-09-25 01:05:10][ERROR: input.scriptfilter] Code 1: 💜
01:05:10 workflow.go:614: ------- Safari Assistant/0.5 (AwGo/0.13.2) -------
01:05:10 cache.go:254: deleted /Users/nikivi/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred.safari/_aw_session.72VOBMVJXJCZ5UQFVQWX7R03.windows
01:05:10 update.go:159: Latest release: 0.5.0
01:05:10 tabs.go:151: query=
01:05:10 workflow.go:627: ------------------ FATAL ERROR -------------------
01:05:10 workflow.go:628: open /Users/nikivi/Library/Safari/Bookmarks.plist: operation not permitted : goroutine 1 [running]:
runtime/debug.Stack(0xc420139858, 0x1, 0x1)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/deanishe/awgo.(*Workflow).Run.func2(0xc4200b2b40)
	/Users/daj/src/github.com/deanishe/awgo/workflow.go:628 +0x11f
panic(0x44ecac0, 0xc42016c720)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/deanishe/go-safari.getParser(0xd0)
	/Users/daj/src/github.com/deanishe/go-safari/safari.go:425 +0x95
github.com/deanishe/go-safari.FilterBookmarks(0x4580338, 0x0, 0xc42016c660, 0x0)
	/Users/daj/src/github.com/deanishe/go-safari/safari.go:441 +0x22
main.customTabActions(0xc4201b8000, 0xc42016c5d0)
	/Users/daj/src/github.com/deanishe/alfred-safari-assistant/tabs.go:235 +0xb2
main.doFilterTabs(0x4564d89, 0x4)
	/Users/daj/src/github.com/deanishe/alfred-safari-assistant/tabs.go:182 +0xfb
main.run()
	/Users/daj/src/github.com/deanishe/alfred-safari-assistant/main.go:421 +0x909
github.com/deanishe/awgo.(*Workflow).Run(0xc4200b2b40, 0x4580370)
	/Users/daj/src/github.com/deanishe/awgo/workflow.go:640 +0x251
main.main()
	/Users/daj/src/github.com/deanishe/alfred-safari-assistant/main.go:477 +0x39
01:05:10 workflow.go:629: ---------------- END STACK TRACE -----------------
01:05:10 feedback.go:431: Sent 1 result(s) to Alfred
01:05:10 workflow.go:760: [ERROR] open /Users/nikivi/Library/Safari/Bookmarks.plist: operation not permitted
01:05:10 workflow.go:763: Get help at https://github.com/deanishe/alfred-safari-assistant/issues
01:05:10 workflow.go:788: --------------------- 0.18s ----------------------
```

**Comment by nikivdev** [comment]
I have permission to Alfred given in System Preferences: 

![2018-09-25 at 10 43](https://user-images.githubusercontent.com/6391776/46003075-f3639680-c0af-11e8-86c6-d9de5ead7ac5.png)

**Comment by deanishe** [comment]
Try adding Alfred to Full Disk Access instead.

**Comment by nikivdev** [comment]
Thanks. That solved it.

**Comment by deanishe** [comment]
Great. Good to know, as I don’t have Mojave.

**Comment by dvcrn** [comment]
I think it might be good to add this to the README. I had the same issue just now

**Comment by deanishe** [comment]
> I think it might be good to add this to the README

If it keeps happening, I will.

It’s such a common requirement across workflows that I tend to see this as more of a matter of general Alfred usage, like knowing where the workflow configuration sheet is, than a workflow-specific thing.

I’d rather not turn each of my workflow READMEs into general “how workflows work” tutorials.
